#PBS -l walltime=00:20:00
#PBS -l select=1:ncpus=1:mem=1gb

ml tools/prod
ml Python
ml Java
ml beagle-lib/4.0.0-GCC-11.3.0
ml R-bundle-CRAN

cd $PBS_O_WORKDIR
source /rds/general/user/jst21/home/m4r/.venv/bin/activate

mkdir -p "$OUTDIR"
mkdir -p "$OUTDIR/$PREFIX"
mkdir -p logs
exec > logs/${PREFIX}.out 2> logs/${PREFIX}.err

echo "Running Python script..."
python program.py "$PREFIX" "$METHOD" "$LEAVES" "$SITES" "$SEED" "$OUTDIR/$PREFIX"

echo "Running BEAST on all generated data..."
cd "$OUTDIR/$PREFIX"
# 060526 run separate jobs in parallel, need to change walltime, ncpus, mem
# java -jar ../../../beast.jar ${PREFIX}_independent.xml > beast_output_indep.txt
# java -jar ../../../beast.jar ${PREFIX}_dependent.xml > beast_output_dep.txt

echo "Running tree comparison..."
cd $PBS_O_WORKDIR
Rscript tree_comparison.r $OUTDIR/$PREFIX

echo "Complete."