#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=16:mem=16gb

ml tools/prod
ml Python
ml Java
ml beagle-lib/4.0.0-GCC-11.3.0
ml R-bundle-CRAN

cd $PBS_O_WORKDIR
source /rds/general/user/jst21/home/m4r/.venv/bin/activate

mkdir -p "$OUTDIR"
mkdir -p "$OUTDIR/$PREFIX"
mkdir -p logs
exec > "logs/${PREFIX}_${PBS_JOBID}.out" 2> "logs/${PREFIX}_${PBS_JOBID}.err"

echo "Running Python script..."
python exp2.py "$PREFIX" "$METHOD" "$LEAVES" "$SITES" "$SEED" "$OUTDIR/$PREFIX"

echo "Running BEAST on all generated data..."
cd "$OUTDIR/$PREFIX"
java -jar ../../../beast.jar -threads 1 independent.xml &
for i in {1..12}
do
  java -jar ../../../beast.jar -threads 1 dependent_${i}.xml &
done
wait

echo "Running tree comparison..."
cd $PBS_O_WORKDIR
Rscript tree_comparison.r $OUTDIR $PREFIX

echo "Complete."