#PBS -S /bin/bash
#PBS -l walltime=00:20:00
#PBS -l select=1:ncpus=1:mem=1gb

ml tools/prod
ml Python

cd $PBS_O_WORKDIR
if [ ! -f setup_val1/val1_config.env ]; then
    echo "Missing setup_val1/val1_config.env in $PBS_O_WORKDIR"
    exit 1
fi

source /rds/general/user/jst21/home/m4r/.venv/bin/activate
source setup_val1/val1_config.env

echo "Running post-processing python script..."
python setup_val1/val1_postprocessing.py \
  "$LEAVES_LIST" \
  "$SEED_LIST" \
  "$SITES_LIST"
echo "Post-processing complete"