#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=1:mem=4gb

ml tools/prod
ml Python
ml Java
ml beagle-lib/4.0.0-GCC-11.3.0
ml R-bundle-CRAN

cd $PBS_O_WORKDIR
source /rds/general/user/jst21/home/m4r/.simenv/bin/activate
source setup_val1/val1_config.env

mkdir -p "$OUTDIR"
mkdir -p "$OUTDIR/$PREFIX"
exec > "$OUTDIR/logs/out/${PREFIX}_${PBS_JOBID}.out" \
     2> "$OUTDIR/logs/err/${PREFIX}_${PBS_JOBID}.err"

echo "Running Python script..."
python setup_val1/val1.py "$PREFIX" "$METHOD" "$LEAVES" "$SITES" "$SEED" "$OUTDIR/$PREFIX" "$BIRTH_RATE" "$DEATH_RATE"

echo "Running BEAST on all generated data..."
cd "$OUTDIR/$PREFIX"
java -jar ../../../beast.jar independent.xml
wait

echo "Cleaning unnecessary files..."
rm -f *.chkpt
rm -f *.citations.txt

cd $PBS_O_WORKDIR

echo "Running tree comparison..."
Rscript setup_val1/tree_comparison.r $OUTDIR $PREFIX

echo "Complete."